config:
  db: db
  networks:
    - type: netty

  validator:
    contract: !emulator
      # balance: 55
      keys:
        - !interop
          count: 16
          # seed: 0
      interopCredentials: true
      # eth1BlockHash: 0x4242424242424242424242424242424242424242424242424242424242424242
#    signer: !insecure
#      keys:
#        - !generate
#          count: 16
#          seed: 0

chainSpec:
  specConstants:
    initialValues:
      GENESIS_SLOT: 0
    miscParameters:
      SHARD_COUNT: 4
      TARGET_COMMITTEE_SIZE: 2
    timeParameters:
      SECONDS_PER_SLOT: 10
      MIN_ATTESTATION_INCLUSION_DELAY: 1
      SLOTS_PER_EPOCH: 4
      SLOTS_PER_HISTORICAL_ROOT: 64

    honestValidatorParameters:
      ETH1_FOLLOW_DISTANCE: 1
    stateListLengths:
      EPOCHS_PER_HISTORICAL_VECTOR: 64
      EPOCHS_PER_SLASHINGS_VECTOR: 64

  specHelpersOptions:
    blsVerify: false
    blsVerifyProofOfPossession: false
    blsSign: false
    enableCache: false
    # for interop, genesis time should be overridden with the specified value, so ignore computation
    computableGenesisTime: true

